import:
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-base-r4.1.yml
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-dom0-r4.1.yml
  - source: QubesOS/qubes-continuous-integration:R4.1/travis-vms-r4.1.yml
language: python
python:
 - '3.7'
install:
 - pip install --quiet -r ci/requirements.txt
 - git clone https://github.com/QubesOS/qubes-linux-utils ~/linux-utils
 - git clone https://github.com/QubesOS/qubes-core-admin-client ~/core-admin-client

jobs:
  include:
    - env: PYTHONPATH=~/core-admin-client:~/linux-utils/imgconverter
      script:
       - python3 -m pylint qubesappmenus
       - python3 -m coverage run -m unittest -v qubesappmenus.tests
    - stage: deploy
      env: DIST_DOM0=fc31 TESTS_ONLY=
      script:
       - codecov -F unittests
       - ~/qubes-builder/scripts/travis-deploy
